REGISTER_BIN=register
REGISTER_OBJF = register.o

REGISTER_AND_UPDATE_BIN=register_and_update
REGISTER_AND_UPDATE_OBJF=register_and_update.o

LIBS=clanApp clanCore clanNetwork

include Makefile.conf

# EOF #

