REGISTER_BIN=register
REGISTER_OBJF = register.o

KEEPALIVE_BIN=keepalive
KEEPALIVE_OBJF = keepalive.o

REGISTER_AND_LIST_BIN=register_and_list
REGISTER_AND_LIST_OBJF=register_and_list.o

LIBS=clanApp clanCore clanNetwork

include Makefile.conf

# EOF #

