# -*- mode: Makefile; -*-
# $Id: Makefile.conf.in,v 1.6 2003/09/16 21:54:04 grumbel Exp $
#
# This file contains all compiler options used to build ClanLib.
#

PACKAGES = $(patsubst %,%-2.1,$(LIBS))
CXXFLAGS += `pkg-config --cflags $(PACKAGES)` -pthread

#REGISTER_BIN contains list of example binaries to build

all: $(REGISTER_BIN) $(REGISTER_AND_UPDATE_BIN) $(REGISTER_AND_LIST_BIN)

$(REGISTER_BIN): $(REGISTER_OBJF)
	$(CXX) $(CXXFLAGS) $(REGISTER_OBJF) -o $(REGISTER_BIN) `pkg-config --libs $(PACKAGES)` $(EXTRA_LIBS)

$(REGISTER_AND_LIST_BIN): $(REGISTER_AND_LIST_OBJF)
	$(CXX) $(CXXFLAGS) $(REGISTER_AND_LIST_OBJF) -o $(REGISTER_AND_LIST_BIN) `pkg-config --libs $(PACKAGES)` $(EXTRA_LIBS)

clean:
	rm -f $(REGISTER_OBJF) $(REGISTER_BIN)
	rm -f $(REGISTER_AND_LIST_OBJF) $(REGISTER_AND_LIST_BIN)

%.o : %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

#configuration settings

